backend:
  name: github
  repo: https://mahfuj863.github.io/MAHFUJ-ALOM/ 
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
